INSERT INTO USERS (ID, USERNAME, FIRSTNAME, LASTNAME, PASSWORD, ROLE) VALUES (-3, 'admin', 'cp', '630', 'cp630', 1);
INSERT INTO USERS (ID, USERNAME, FIRSTNAME, LASTNAME, PASSWORD, ROLE) VALUES (-4, 'me', 'h', 'f', 'cp630', 2);
INSERT INTO USERS (ID, USERNAME, FIRSTNAME, LASTNAME, PASSWORD, ROLE) VALUES (-5, 'guest', 'w', 'l', 'guest', 3);